// Project: CS 460 Fall 2020 Project 3
// File: Code_Generator.cpp
// Author: Dr. Watts
// Documented by:
// Desciption: Code Generator class for Scheme to C++ translation

#include <iostream>
#include <fstream>
#include "Code_Generator.h"

using namespace std;

Code_Generator::Code_Generator (string filename, Lexical_Analyzer * L)
{
	lex = L;
	string cppname = filename.substr (0, filename.length()-3) + ".cpp"; 
	cpp.open (cppname.c_str());
	cpp << "// Autogenerated Scheme to C++ Code\n";
	cpp << "// File: " << cppname << "\n";
	cpp << "#include <iostream>\n";
	cpp << "#include \"Object.h\"\n";
	cpp << "using namespace std;\n\n";
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
Code_Generator::~Code_Generator ()
{
	cpp.close();
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
void Code_Generator::WriteCode (int tabs, string code)
{
	for (int t = 0; t < tabs; t++)
		cpp << '\t';
	cpp << code;
}
