// Autogenerated Scheme to C++ Code
// File: ./P3-4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main ()
{
	Object __RetVal;
	cout << (Object(6) + Object(3));
	cout << endl;
	cout << (Object(4.1) + Object(2.5));
	cout << endl;
	cout << (Object(4.7) + Object(2.5));
	cout << endl;
	cout << (Object(6) - Object(3));
	cout << endl;
	cout << (Object(4.1) - Object(2.5));
	cout << endl;
	cout << (Object(4.7) - Object(2.5));
	cout << endl;
	cout << (Object(6) * Object(3));
	cout << endl;
	cout << (Object(4.1) * Object(2.5));
	cout << endl;
	cout << (Object(4.7) * Object(2.5));
	cout << endl;
	cout << (Object(6) / Object(3));
	cout << endl;
	cout << (Object(4.1) / Object(2.5));
	cout << endl;
	cout << (Object(4.7) / Object(2.5));
	cout << endl;
	cout << (Object(6) % Object(3));
	cout << endl;
	cout << (Object(14) % Object(8));
	cout << endl;
	cout <<  round (Object(6.3));
	cout << endl;
	cout <<  round (Object(14.8));
	cout << endl;
	return 0; 
}
