// Autogenerated Scheme to C++ Code
// File: test5.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function1()
{
	Object __RetVal;
	__RetVal = Object(6);
	return __RetVal; 
}
int main ()
{
	Object __RetVal;
	cout << function1();
	cout << endl;
	return 0; 
}
