// Autogenerated Scheme to C++ Code
// File: P3-2.cpp
#include <iostream>
#include "Object.h"
using namespace std;


int main ()
{
	Object __RetVal;
	cout << Object("(hello 12.3 append if display newline car define number? list? zero? null? string? )");
	cout << endl;
	cout << Object("(+ - / * modulo round = > < >= <= cond else )");
	cout << endl;
	cout << Object("(1 Hello world 2 ac 3 (and or not ) )");
	cout << endl;
	return 0;
}
