// Autogenerated Scheme to C++ Code
// File: P3-5.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object function1 (Object V)
{
	Object __RetVal;
	cout << V;
	cout << endl;
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	__RetVal = function1(Object(5));
	__RetVal = function1(Object("a"));
	__RetVal = function1(Object("SSU"));
	__RetVal = function1(Object("(1 2 3 )"));
	return 0;
}
