// Autogenerated Scheme to C++ Code
// File: P3-9.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object arithmetic (Object a, Object b, Object c)
{
	Object __RetVal;
	__RetVal = (((a + Object(2)) * (b + Object(3)) * (c + Object(4))) + (a / b) + (round ((c / b)) % Object(2)) + (a - b - c));
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	cout << arithmetic(Object(1.0), Object(3.0), Object(5.0));
	cout << endl;
	cout << arithmetic(Object(1.1), Object(3.3), Object(5.5));
	cout << endl;
	return 0;
}
