// Autogenerated Scheme to C++ Code
// File: P3-A.cpp
#include <iostream>
#include "Object.h"
using namespace std;


Object funky (Object p, Object ls)
{
	Object __RetVal;
	{
		Object v = (Object(2) * p);
		if ((v <= Object(10)))
		{
			if ((v > Object(5)))
			{
				__RetVal = ((v) * (v));
			}
			else
			{
				__RetVal = round ((v / (v % Object(3))));
			}
;
		}
		else 		if ((v == Object(11)))
		{
			__RetVal = listop ("cons", v, ls);
		}
		else 		if ((v < Object(13)))
		{
			__RetVal = listop ("cdar", ls);
		}
		else 		if ((numberp (v) || listp (ls) || zerop (v) || stringp (v)))
		{
			__RetVal = v;
		}
		else 
		{
			if (nullp (ls))
			{
				__RetVal = Object("empty");
			}
		}
	}
	return __RetVal;
}

int main ()
{
	Object __RetVal;
	if (((Object(7) >= Object(5)) && ! ((Object(5) >= Object(7)))))
	{
		cout << funky(Object(5), Object("(a 5 hello world cons if display newline cadr and or not define  number? list? zero? null? string? + - / * modulo round = > < >= <= cond else )"));
	}
	cout << endl;
	return 0;
}
