// Autogenerated Scheme to C++ Code
// File: ./P3-7.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function1(Object V1, Object V2)
{
	Object __RetVal;
	if ((V1 < V2)){ 
 	cout << (V1 + V2);
	}
	else 	if ((V1 > V2)){ 
 	cout << (V1 - V2);
	}
	else 	if ((V1 == V2)){ 
 	cout << (V1 * V2);
	}
	return __RetVal; 
}
int main ()
{
	Object __RetVal;
	__RetVal = function1(Object(3), Object(5));
	cout << endl;
	__RetVal = function1(Object(13), Object(5));
	cout << endl;
	return 0; 
}
