// Autogenerated Scheme to C++ Code
// File: test2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main ()
{
	Object __RetVal;
	cout << Object(3.14159);
	cout << endl;
	return 0; 
}
