// Autogenerated Scheme to C++ Code
// File: test6.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function1(Object V1, Object V2)
{
	Object __RetVal;
	if ((V1 < V2))
	{
(V1 + V2)	}
	else {
(V1 * V2)	}
	return __RetVal; 
}
int main ()
{
	Object __RetVal;
	cout << 	__RetVal = function1(Object(3), Object(6));
; //DIsplAY!!! 
	cout << endl;
	cout << 	__RetVal = function1(Object(14), Object(6));
; //DIsplAY!!! 
	cout << endl;
	return 0; 
}
