// Autogenerated Scheme to C++ Code
// File: test3.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main ()
{
	Object __RetVal;
	cout << ((Object(4) / Object(2)) + (Object(10) - Object(2))(Object(2) * Object(2) * Object(2) * Object(2))); //DIsplAY!!! 
	cout << endl;
	return 0; 
}
